title: Pearyman
subtitle: "Born to create better beautiful documents"
description: "Born to create better beautiful documents"
logo: 'http://ac-a5zjlnxg.clouddn.com/55ff48114503cdab7564.svg'
language:
- zh-cn
timezone: UTC
url: http://pearyman.com
root: /
archive_dir: news
permalink: news/:year/:month/:day/:title/
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: false
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pearyman

less:
  compress: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
